### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by Feng00148** [soonwoohong/Deep-learning-for-EGFR-trajectory-classification#1]
We noticed that your research is well done, but the original dataset is not included in this project, only the preprocessed dataset. Sincerely hope you can share the original dataset of 13,652 observations mentioned in the original paper into this project as well. Thank you!

**Comment by soonwoohong** [comment]
Thank you for showing interest on our project. Unfortunately, we are not sharing our original dataset, but you can use the preprocessed dataset for demonstration.
